SPHINX_PROJECT_NAME=XMOS Brushed DC and Stepper motor examples
VERSION=1.0.0
DOXYGEN_DIRS=../app_DC_motor ../app_stepper_motor
SOURCE_INCLUDE_DIRS=..
XDOC_DIR ?= ../../xdoc
BREADCRUMB_PREFIX=<li><a href="../../index.html">Home</a></li>
XDEDOC_TITLE_PREFIX=MC
include $(XDOC_DIR)/Makefile.inc
